### PR TITLE
updated msgpack library

### LINKED ISSUE #1: Nuget .Net Core Version?
Looks like the project could/should support .NetStandard. Also, what do you think about using [MessagePack-CSharp](https://github.com/neuecc/MessagePack-CSharp)? I created a serializer using it and it works well. I can submit a PR if you would like with the requested changes.

### PR DESCRIPTION
**Pull request by ahmet8282**
Fixed #1 

The tests are passing, so I guess everything works.

---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by mookid8000** [comment]
Hi @ahmettahasakar , could you go and update your GitHub profile and add the email address, you're using in Git? That way, GitHub can link your commits to your GitHub identity, and the CLA assistant think will work...

You can tell that GitHub doesn't know you when you look at [your commit](https://github.com/rebus-org/Rebus.MsgPack/pull/2/commits/4f034b964f299152ad711a685cfbf7b4ce2ff527), and it just says "Ahmet Taha Sakar" without providing a link to your GitHub profile.

**Comment by ahmet8282** [comment]
Hello,

Ok. It looks signed now.

**Comment by mookid8000** [comment]
Perfect 👍 it's out in Rebus.MsgPack 5.0.0-b1 on NuGet.org now

I'll publish it as a proper version when you have tried it, and you have determined that it works as it should.

**Comment by ahmet8282** [comment]
Not there yet. Still waiting

https://www.nuget.org/packages/Rebus.MsgPack/

**Pull request merged**
